<h1>Numpy Basics</h1>

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
b = np.array([1,2,3,4,5],dtype = "float32")
b

array([1., 2., 3., 4., 5.], dtype=float32)

##### numpy : SIMD - Single Input Multple Data

In [8]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
#Dimension of the array or matrix
print(a.ndim)
print(c.ndim)

1
2


In [11]:
# Shape
print(a.shape)
print(c.shape)

(5,)
(2, 5)


In [12]:
print(b.dtype)
print(a.dtype)

float32
int64


In [14]:
print(a.size)
print(c.size)

5
10


In [18]:
#  bit size of the element
print(a.itemsize)

8


In [20]:
# Total size of the array
print(a.itemsize * a.size)   #each element is of 8 bytes

40


In [21]:
a.nbytes

40

##### Accessing/Changing specific elements,rows, colums etc

In [24]:
a1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
# Get a specific element/access
print(a1[0,1]) # (row,column)

2


In [26]:
a1[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
a1[0,:]

array([1, 2, 3, 4, 5])

In [29]:
a1[:,1]

array([2, 7])

In [34]:
a1[0, 2:4]

array([3, 4])

In [38]:
a1[0,2] = 30
a1

array([[ 1,  2, 30,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [49]:
a1[:,1:2]
a1

array([[ 1,  5, 30,  4,  5],
       [ 6,  5,  8,  9, 10]])

*3d example

In [51]:
d = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [52]:
d.ndim

3

In [53]:
d.size

8

In [54]:
d.shape

(2, 2, 2)

In [55]:
d.nbytes

64

##### Accessing

In [56]:
d[1,1,1]

8

In [59]:
# replace
d[:,:,1] = 50
d

array([[[ 1, 50],
        [ 3, 50]],

       [[ 5, 50],
        [ 7, 50]]])

##### Initializing Different types of arrays

In [65]:
z = np.zeros((2,3),dtype = 'int16')
print(z)

[[0 0 0]
 [0 0 0]]


In [67]:
o = np.ones((2,3),dtype = 'int16')
print(o)

[[1 1 1]
 [1 1 1]]


* 3-d

In [73]:
zz = np.zeros((2,3,3))
print(zz)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [88]:
# any other number
an = np.full((2,3,3),100)
print(an)
print(an.shape)
ans = np.full(an.shape,110)
ans

[[[100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [100 100 100]
  [100 100 100]]]
(2, 3, 3)


array([[[110, 110, 110],
        [110, 110, 110],
        [110, 110, 110]],

       [[110, 110, 110],
        [110, 110, 110],
        [110, 110, 110]]])

In [86]:
an_lik = np.full_like((zz),200)
print(an_lik)

[[[200. 200. 200.]
  [200. 200. 200.]
  [200. 200. 200.]]

 [[200. 200. 200.]
  [200. 200. 200.]
  [200. 200. 200.]]]


In [97]:
# Random decimal
de = np.random.rand(2,3)
de
de.shape

(2, 3)

In [100]:
de = np.random.random_sample(de.shape)   # for sampling another array
de

array([[0.84998419, 0.89740356, 0.76090886],
       [0.12987203, 0.22230263, 0.03655785]])

In [117]:
# Random integers values
dei = np.random.randint(100,size=(3,3))
print(dei)

[[87 11 77]
 [88 93 15]
 [94 84 95]]


In [119]:
i = np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [124]:
# Repeating a matrix
r1 = np.repeat(i,2,axis = 1)
r1

array([[1., 1., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 1., 1.]])

In [137]:
p = np.ones((5,5),dtype = "int32")
p

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [132]:
p1 = np.zeros((3,3),dtype='int16')
p1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [133]:
p1[1,1] = 9

In [134]:
p1

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]], dtype=int16)

In [138]:
p

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [139]:
p[1:4,1:4] = p1

In [141]:
print(p)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


##### Becareful about the copying matrix


In [142]:
a = [1,2,3]
b = a
b[2] = 30
print(a)
print(b)

[1, 2, 30]
[1, 2, 30]


In [144]:
#instead
b = a.copy()
b[2] = 3
print(b)
print(a)

[1, 2, 3]
[1, 2, 30]


##### Maths

In [163]:
mat = np.array([1,2,3,4,5,6])
mat

array([1, 2, 3, 4, 5, 6])

In [149]:
mat+2

array([3, 4, 5, 6, 7, 8])

In [150]:
mat

array([1, 2, 3, 4, 5, 6])

In [151]:
mat-2

array([-1,  0,  1,  2,  3,  4])

In [152]:
mat*2

array([ 2,  4,  6,  8, 10, 12])

In [153]:
mat/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [154]:
mat**2

array([ 1,  4,  9, 16, 25, 36])

In [164]:
mat

array([1, 2, 3, 4, 5, 6])

In [165]:
mat+=2
mat

array([3, 4, 5, 6, 7, 8])

In [180]:
# We can do the matrix manipulations
mat2 = np.array([
    [1],
    [2],
    [3],
    [4],
    [5],
    [6]]
               )
# print(mat)
# print(mat2)
# print(mat2 + mat,"\n")
# print(mat-mat2,"\n")
print(np.matmul(mat,mat2),"\n")


[133] 



In [183]:
np.cos(mat)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029,  0.75390225,
       -0.14550003])

##### Linear  Algebra

In [202]:
# Determinant of a matrix
c = np.random.randint(10,size = (2,2),dtype = 'int16')
print(c)
np.linalg.det(c)

[[5 3]
 [6 8]]


21.999999999999996

In [204]:
c.T # Transpose

array([[5, 6],
       [3, 8]], dtype=int16)

In [216]:
 """include
determinant
trace
singular vector decomposition
eigenvalue
matrix norm
inverese
etc.


"""

'include\ndeterminant\ntrace\nsingular vector decomposition\neigenvalue\nmatrix norm\ninverese\netc.\n\n\n'

In [233]:
# dot product or scalar product
v1 = np.array([1,2,3])
v2 = np.array([1,2,3])
result = v1.dot(v2)
result   # multi and add

14

In [234]:
# Inverse of a Matrix
v1 = np.array([[1,2,3],[3,2,1],[1,2,2]])
v1_inv = np.linalg.inv(v1)
v1_inv

array([[ 0.5 ,  0.5 , -1.  ],
       [-1.25, -0.25,  2.  ],
       [ 1.  , -0.  , -1.  ]])

In [247]:
# Solving a system of linear equations
# Solving v1x = v2 for x  (Solving the argumented matrix resulting the simplified (GJEM))
v2 = np.array([[1,2,3],[3,2,1],[2,1,3]])
x = np.linalg.solve(v1,v2)
x

array([[ 0.,  1., -1.],
       [ 2., -1.,  2.],
       [-1.,  1., -0.]])

In [248]:
# Eigen Values and Eigen vectors
eig_val, eig_vec = np.linalg.eig(v1)
print(eig_val)
print("\nEigen-Vectors : \n")
print(eig_vec)

[ 5.65551489+0.j         -0.32775745+0.77449938j -0.32775745-0.77449938j]

Eigen-Vectors : 

[[ 0.59431599+0.j          0.45043272-0.26810827j  0.45043272+0.26810827j]
 [ 0.62589464+0.j         -0.73515524+0.j         -0.73515524-0.j        ]
 [ 0.50501922+0.j          0.35996492+0.23494754j  0.35996492-0.23494754j]]


##### Statistics

In [249]:
stat = np.array([
    [1,2],
    [3,4],
    
])
stat

array([[1, 2],
       [3, 4]])

In [252]:
mini = np.min(stat)
maxi = np.max(stat)
print(mini)
print(maxi)

1
4


In [255]:
# Along the row
maxr = np.max(stat,axis = 0)
minr = np.min(stat,axis = 0)
print(minr)
print(maxr)

[1 2]
[3 4]


In [258]:
# Along the column
minc = np.min(stat,axis = 1)
maxc = np.max(stat,axis = 1)
print(minc)
print(maxc)

[1 3]
[2 4]


In [259]:
print(stat > 2)

[[False False]
 [ True  True]]


In [265]:
sums1 = np.sum(stat,axis = 0) # Row-wise sum
sums = np.sum(stat) # Total sum 
print(sums1)
sums

[4 6]


10

In [270]:
# Certain elements sum
v = stat[1:2,:]
print(np.sum(v))

7


##### Reorganizing Arrays

In [274]:
# Reshape but size is same
before = np.array([[1,2,3],[3,2,1]])
print(before)
print(before.size)
after = before.reshape(3,2)
print(after)
print(after.size)

[[1 2 3]
 [3 2 1]]
6
[[1 2]
 [3 3]
 [2 1]]
6


In [277]:
# Vertical Stacking
sta_v = np.vstack([stat,stat])
sta_v

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [278]:
# Horizontal Stack
sta_h = np.hstack([stat,stat])
sta_h

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

### Miscellaneous

##### Load data from a file

In [284]:
data = np.genfromtxt("data.txt",delimiter = ",",dtype = "int32")
data

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  15, 123, 123,  12,  12,   1]],
      dtype=int32)

##### Booleans and Indexing

In [288]:
data[data>2]
# data will be in the series type instead of teh data frame

array([  3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  15, 123, 123,  12,  12], dtype=int32)

In [299]:
# Indexing using lists
ser = np.array([1,2,3,4,5])
print(ser[[0,3,2,1]])
print(stat)
stat[[0,1],[1,1]]  # row, column

[1 4 3 2]
[[1 2]
 [3 4]]


array([2, 4])